import type { TemplateLibraryTableRowType } from "./types";

export const demoTableData2 : unknown[] = [
  {
    template_icon: { 
        type: 'Assigned',
    },
    template_name: { 
        name: '5-S Audit All Departments- 5S Certification Audits',
        type: 'Audit org',
        status: 'Assigned',
    },
    template_id: 'TT-59141',
    created: '05/26/21',
    last_modified: '12/01/22',
  },
  {
    template_icon: { 
        type: 'Checklist',
    },
    template_name: { 
        name: 'Cut Fruit/Cut Melon Presentation',
        type: 'Checklist',
        status: 'Assigned',
    },
    template_id: 'TT-60142',
    created: '05/26/21',
    last_modified: '12/01/22',
  },
  {
    template_icon: { 
        type: 'Checklist',
    },
    template_name: { 
        name: 'D2 LA County Maximum Occupancy- 031521',
        type: 'Checklist',
        status: 'Assigned',
    },
    template_id: 'TT-71143',
    created: '05/26/21',
    last_modified: '12/01/22',
  },
  
];

export const folderTreeData = {
    "success": true,
    "message": "Tags fetched successfully for role: ADMIN",
    "data": [
        {
            "tagId": 23,
            "tagName": "Templates",
            "tagType": "Task_Library",
            "tagSort": null,
            "tagLevel": 1,
            "isPublic": true,
            "isPrivate": true,
            "isHidden": true,
            "isNoShow": false,
            "reportType": null,
            "isExpanded": true,
            "children": [
                {
                    "tagId": 2020,
                    "tagName": "Nathaniel example",
                    "tagType": "Message_Board_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": null,
                    "children": [
                        {
                            "tagId": 2023,
                            "tagName": "test",
                            "tagType": "Message_Board_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": null,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 101,
                    "tagName": " *Assigned Tasks*",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 3003,
                            "tagName": "Henry Task template Test",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": true,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 2018,
                    "tagName": ".Queue Management",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3001,
                    "tagName": "Customer Tasks",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3005,
                    "tagName": "Investigation",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3006,
                    "tagName": "Heartbeat",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3009,
                    "tagName": "3.0 Connect Tests",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3010,
                    "tagName": "Test Templates",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 3011,
                            "tagName": "Jens Tests",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 3012,
                    "tagName": "UI_TESTING",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 2003,
                    "tagName": "Demo",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 1013,
                            "tagName": "Alex Lee Demo Tasks",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2004,
                            "tagName": "Client examples",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": [
                                {
                                    "tagId": 3013,
                                    "tagName": "Cleaning floor",
                                    "tagType": "Task_Library",
                                    "tagSort": null,
                                    "tagLevel": 3,
                                    "isPublic": true,
                                    "isPrivate": true,
                                    "isHidden": true,
                                    "isNoShow": false,
                                    "reportType": null,
                                    "isExpanded": true,
                                    "children": []
                                }
                            ]
                        },
                        {
                            "tagId": 2005,
                            "tagName": "Ross",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2007,
                            "tagName": "Albertsons",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2009,
                            "tagName": "Scotmid",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2010,
                            "tagName": "Heinen's",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2026,
                            "tagName": "Product updates",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 3004,
                            "tagName": "Grind",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 3008,
                            "tagName": "Inventory",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 2011,
                    "tagName": "Archive",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": true,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 116,
                    "tagName": "Standard Templates",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 117,
                            "tagName": "Operational Processes",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 118,
                            "tagName": "Compliance Tasks",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 119,
                            "tagName": "Performance Mangement",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 121,
                            "tagName": "External Tasks",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 123,
                            "tagName": "Corporate Quick Tasks",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 1019,
                            "tagName": "Incident Management",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2001,
                            "tagName": "Tickets (demo)",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2002,
                            "tagName": "Food safety",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": [
                                {
                                    "tagId": 2025,
                                    "tagName": "Sanitation",
                                    "tagType": "Task_Library",
                                    "tagSort": null,
                                    "tagLevel": 3,
                                    "isPublic": true,
                                    "isPrivate": true,
                                    "isHidden": true,
                                    "isNoShow": false,
                                    "reportType": null,
                                    "isExpanded": false,
                                    "children": []
                                }
                            ]
                        }
                    ]
                },
                {
                    "tagId": 2019,
                    "tagName": ".Store Conditions",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 2017,
                    "tagName": ".Food Safety",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 120,
                    "tagName": "Standard Templates",
                    "tagType": "Message_Board_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": null,
                    "children": [
                        {
                            "tagId": 2021,
                            "tagName": "New Folder",
                            "tagType": "Message_Board_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": null,
                            "children": []
                        },
                        {
                            "tagId": 2022,
                            "tagName": "test directory",
                            "tagType": "Message_Board_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": false,
                            "isHidden": false,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": null,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 2015,
                    "tagName": "Incident Management",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 2006,
                    "tagName": "Videos",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 2014,
                    "tagName": "Food Safety resources",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 2008,
                            "tagName": "Food Safety Training",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2024,
                            "tagName": "Sensor Management",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 3002,
                            "tagName": "Testing ( do not delete)",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 3007,
                            "tagName": "PS_Sandbox",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 2016,
                    "tagName": "Store operations Solution",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                }
            ]
        },
        {
            "tagId": 3000,
            "tagName": "IMS Tasks",
            "tagType": "Task_Library",
            "tagSort": "000|000|000",
            "tagLevel": 1,
            "isPublic": true,
            "isPrivate": true,
            "isHidden": true,
            "isNoShow": false,
            "reportType": null,
            "isExpanded": true,
            "children": []
        },
        {
            "tagId": 76,
            "tagName": "Report Task",
            "tagType": "Task_Library",
            "tagSort": "000|000|000",
            "tagLevel": 1,
            "isPublic": true,
            "isPrivate": true,
            "isHidden": true,
            "isNoShow": false,
            "reportType": null,
            "isExpanded": true,
            "children": [
                {
                    "tagId": 77,
                    "tagName": "Execution",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 103,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 78,
                    "tagName": "Score",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 9,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 79,
                    "tagName": "Compliance",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 104,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 80,
                    "tagName": "Detail",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 10,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 122,
                    "tagName": "Metric",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 105,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 1001,
                    "tagName": "Sales and Labor",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": -1,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 1017,
                    "tagName": "Metric Distinct",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 106,
                    "isExpanded": null,
                    "children": []
                },
              ]
            }
    ]
  }

export const demoTableData: TemplateLibraryTableRowType[] = [
        {
            "templateId": 1894,
            "tagId": 2002,
            "templateName": "Cook Log (>165) (from launch task)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:24:42",
            "lastModifiedTime": "2019-07-10T17:20:52.223",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 1897,
            "tagId": 2003,
            "templateName": "Cook Log (>145) (from launch task)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:24:42",
            "lastModifiedTime": "2019-07-10T17:33:38.503",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 1899,
            "tagId": 2004,
            "templateName": "Cook Log (>90) (from launch task)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:24:42",
            "lastModifiedTime": "2019-12-18T15:40:32.097",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 1973,
            "tagId": 2005,
            "templateName": "Discard product",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2017-11-16T13:35:28",
            "lastModifiedTime": "2019-08-01T15:52:25.28",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 1981,
            "tagId": 2006,
            "templateName": "Cool Down Interval - 2 hr.",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:33:18",
            "lastModifiedTime": "2020-01-15T16:46:34.95",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2091,
            "tagId": 2007,
            "templateName": "Cook Log (>145)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:24:42",
            "lastModifiedTime": "2019-07-10T17:29:08.833",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2172,
            "tagId": 2008,
            "templateName": "Cook Log (>165)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:24:42",
            "lastModifiedTime": "2019-07-10T17:27:12.597",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2203,
            "tagId": 2009,
            "templateName": "Hot Bar Temp Check (location scan)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2018-09-26T22:30:49.677",
            "lastModifiedTime": "2020-07-17T18:51:41.612",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2205,
            "tagId": 2010,
            "templateName": "Cook Log (>90)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:24:42",
            "lastModifiedTime": "2020-08-05T10:23:10.096",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2207,
            "tagId": 2011,
            "templateName": "Two-Hour Hot Hold Interval (>80)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2017-11-16T13:33:18",
            "lastModifiedTime": "2020-07-17T22:17:45.636",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2208,
            "tagId": 2012,
            "templateName": "Two-Hour Hot Hold Interval (subsequent)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2017-11-16T13:33:18",
            "lastModifiedTime": "2020-07-17T22:18:03.692",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2217,
            "tagId": 2013,
            "templateName": "Discard product (after intermediate step)",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2017-11-16T13:35:28",
            "lastModifiedTime": "2019-11-13T12:09:10.14",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 2222,
            "tagId": 2014,
            "templateName": "Corrective Action (item scan >38)",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2019-07-10T23:23:04.473",
            "lastModifiedTime": "2019-11-13T11:39:13.667",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 2223,
            "tagId": 2015,
            "templateName": "Corrective Action (item scan >41)",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2019-07-10T23:23:04.473",
            "lastModifiedTime": "2019-11-13T11:40:47.793",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 2226,
            "tagId": 2016,
            "templateName": "Discard product copy",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2017-11-16T13:35:28",
            "lastModifiedTime": "2019-08-01T15:52:25.28",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 2234,
            "tagId": 2017,
            "templateName": "Corrective Action (item scan >40)",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2019-07-10T23:23:04.473",
            "lastModifiedTime": "2019-11-13T11:40:01.233",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 2243,
            "tagId": 2018,
            "templateName": "Hot Bar Corrective Action – Pull product",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2019-12-18T13:21:46.753",
            "lastModifiedTime": "2020-07-20T10:35:58.461",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 2278,
            "tagId": 2019,
            "templateName": "Cool Down Interval - 6 hr.",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:33:18",
            "lastModifiedTime": "2020-06-15T17:12:38.036",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2283,
            "tagId": 2020,
            "templateName": "Deli Temp Check (item scan)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2019-05-06T17:32:34.447",
            "lastModifiedTime": "2020-07-10T15:33:42.971",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2289,
            "tagId": 2021,
            "templateName": "Cook/Cool On Demand Step 1 (Wegmans)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2020-02-03T16:05:54.72",
            "lastModifiedTime": "2020-07-17T18:36:56.054",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2290,
            "tagId": 2022,
            "templateName": "Cook/Cool On Demand Step 2 (Wegmans)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2020-02-03T16:09:43.537",
            "lastModifiedTime": "2020-07-17T18:45:05.052",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2291,
            "tagId": 2023,
            "templateName": "Hot Bar Temp Check (item scan)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2019-05-06T17:32:34.447",
            "lastModifiedTime": "2020-07-17T18:51:07.731",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2292,
            "tagId": 2024,
            "templateName": "Initiate Cook Log",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2018-11-01T10:30:29.797",
            "lastModifiedTime": "2020-07-17T18:52:51.822",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2293,
            "tagId": 2025,
            "templateName": "Item Cold Holding (<40)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2018-09-25T11:22:46.113",
            "lastModifiedTime": "2020-07-17T18:59:32.216",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2294,
            "tagId": 2026,
            "templateName": "Rechill Product (<38)",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2018-09-27T09:11:40.997",
            "lastModifiedTime": "2020-07-20T10:33:37.88",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 2295,
            "tagId": 2027,
            "templateName": "Rechill Product (<40)",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2018-09-27T09:11:40.997",
            "lastModifiedTime": "2020-07-20T10:33:53.677",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 2296,
            "tagId": 2028,
            "templateName": "Cook/Cool On-Demand Step 3 (Wegmans)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2020-02-03T16:12:19.937",
            "lastModifiedTime": "2020-07-17T18:44:19.055",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2297,
            "tagId": 2029,
            "templateName": "Hot Bar Temp Check (by cases)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2018-10-30T14:18:39.917",
            "lastModifiedTime": "2021-10-15T16:11:45.055",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2298,
            "tagId": 2030,
            "templateName": "Homestyle Cook/Cool",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2019-07-10T17:11:09.977",
            "lastModifiedTime": "2021-10-28T14:22:25.64",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
    ]